### ISSUE TITLE
Add Simple ReadMe [Documentation]

### ISSUE THREAD

**Issue by miikkuu** [miikkuu/vastram-fashionsite#2]
Add Simple ReadMe [Documentation] Related to the Website

**Comment by the-amazing-atharva** [comment]
Hi!
I am a beginner here and would like to contribute

**Comment by miikkuu** [comment]
@the-amazing-atharva Thanks for Checking.
 For sure! Go ahead!...Have a look at the page once and Accordingly add the Readme.
Add Basic Intro to site , Features and Contribution section (which invites people for contributing in different sections like Docs , WebD , Backend etc).
Do as much you understand And don't hesitate to ask out when required.
Fork -> Clone -> Make a Branch -> Make the Changes -> Push the Code - > and Finally Submit a PR and that's it!
If everything is fine I will be merging in your PR.

**Comment by miikkuu** [comment]
@the-amazing-atharva Are you in?

**Comment by the-amazing-atharva** [comment]
Yes !

Working on it now

Sorry for the late reply

**Comment by the-amazing-atharva** [comment]
Thanks for merging bro

Should I add a license #4 and CONTRIBUTING,md #5 ?

**Comment by miikkuu** [comment]
Thank You @the-amazing-atharva sure do it ...also in the Contributors section add your icon as well.

**Comment by the-amazing-atharva** [comment]
Sure!
