### ISSUE TITLE
Add DockerFile !

### ISSUE THREAD

**Issue by miikkuu** [miikkuu/vastram-fashionsite#8]
add simple docker file for running the project in a container

**Comment by ShashwatAgrawal20** [comment]
Hey, I would like to give this a shot

**Comment by miikkuu** [comment]
@ShashwatAgrawal20  Go ahead! Let me know if you need any help. 
btw its a simple frontend part of a traditional clothing website so its really damn simple few lines into dockerfile to generate it.

**Comment by ShashwatAgrawal20** [comment]
yeah,btw you have some nice designing skills
